apiVersion: v1
kind: Service
metadata:
  name: analytics-api
spec:
  type: LoadBalancer
  selector:
    service: analytics-api
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  labels:
    service: analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: analytics-api
  template:
    metadata:
      labels:
        service: analytics-api
    spec:
      containers:
      - name: analytics-api
        image: 129006319628.dkr.ecr.us-east-1.amazonaws.com/coworking:18
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
          - secretRef:
              name: dbsecret
          - configMapRef:
              name: dbconfigmap
      restartPolicy: Always